"""Add Paystack integration fields to subscription plans

Revision ID: 72ebb93141dc
Revises: 0f1d78585246
Create Date: 2025-08-24 03:56:17.041170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ebb93141dc'
down_revision = '0f1d78585246'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('paystack_plan_code_monthly', sa.String(length=100), nullable=True))
    op.add_column('subscription_plans', sa.Column('paystack_plan_code_yearly', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'paystack_plan_code_yearly')
    op.drop_column('subscription_plans', 'paystack_plan_code_monthly')
    # ### end Alembic commands ###
