"""add_grace_period_and_usage_reset_fields

Revision ID: a9cad5248ac1
Revises: 72ebb93141dc
Create Date: 2025-08-24 13:43:07.564480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cad5248ac1'
down_revision = '72ebb93141dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
