"""add_grace_period_fields_manual

Revision ID: d3a8e684cbb5
Revises: a9cad5248ac1
Create Date: 2025-08-24 14:11:38.817767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a8e684cbb5'
down_revision = 'a9cad5248ac1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('downgrade_to_plan_id', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('downgrade_effective_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('last_invoice_reset_date', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'subscription_plans', ['downgrade_to_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'last_invoice_reset_date')
    op.drop_column('subscriptions', 'downgrade_effective_date')
    op.drop_column('subscriptions', 'downgrade_to_plan_id')
    # ### end Alembic commands ###
